@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.obsidian_core.archaic_quest.common.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;