modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId = "archaic_quest"
version = "${file.jarVersion}"
displayName = "Archaic Quest"
logoFile = "icon.png"
credits = "Obsidian Core and the other peeps"
authors = "Obsidian Core, Sarinsa, Tate___Langdon"
description = "Obsidian Core's legacy, with some other stuff."

[[dependencies.archaic_quest]]
modId = "forge"
mandatory = true
versionRange = "[47.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archaic_quest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archaic_quest]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.1.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archaic_quest]]
modId = "ryoamiclights"
mandatory = false
versionRange = "[0.2.3,)"
ordering = "NONE"
side = "BOTH"
