modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
    modId="archaic_quest"
    version="${file.jarVersion}"
    displayName="Archaic Quest"
    logoFile="examplemod.png"
    credits="Obsidian Core and the other peeps"
    authors="Obsidian Core, Sarinsa, Tate___Langdon"
    description="Obsidian Core's legacy, with some other stuff."

[[dependencies.archaic_quest]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.archaic_quest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
