@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.obsidian_core.archaic_quest.common.block.base;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;