@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.obsidian_core.archaic_quest.common.item.blockitem;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;