@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.obsidian_core.archaic_quest.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;