@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.obsidian_core.archaic_quest.common.entity.projectile;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;